Loading Data set from Kaggle

In [2]:
import numpy as np
import pandas as pd

rating=pd.read_csv('Ratings.csv')
user=pd.read_csv('Users.csv')
book=pd.read_csv('Books.csv')

C:\Users\Anika\AppData\Local\Temp\ipykernel_17336\3269448113.py:6: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  book=pd.read_csv('Books.csv')

Cleaning and Preprocessing

In [4]:
book.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [5]:
user.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [6]:
rating.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [7]:
print(book.shape)
print(user.shape)
print(rating.shape)

(271360, 8)
(278858, 3)
(1149780, 3)

In [8]:
book.duplicated().sum()

0

In [9]:
user.duplicated().sum()

0

In [10]:
rating.duplicated().sum()

0

In [11]:
book.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [12]:
user.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [13]:
rating.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [14]:
user.columns

Index(['User-ID', 'Location', 'Age'], dtype='object')

In [15]:
rating.columns

Index(['User-ID', 'ISBN', 'Book-Rating'], dtype='object')

In [16]:
book.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')

In [17]:
book.dtypes

ISBN                   object
Book-Title             object
Book-Author            object
Year-Of-Publication    object
Publisher              object
Image-URL-S            object
Image-URL-M            object
Image-URL-L            object
dtype: object

In [18]:
user.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [19]:
book.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [20]:
book=book.rename(columns={'Book-Author':'Author',
                    'Year-Of-Publication':'Published-Year',
                    'Book-Title':'Title',
                    'Image-URL-S':'URL-S',
                    'Image-URL-M':'URL-M',
                    'Image-URL-L':'URL-L'
                    })

In [21]:
rating.head(3)

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0

In [22]:
user.head(13)

    User-ID                            Location   Age
0         1                  nyc, new york, usa   NaN
1         2           stockton, california, usa  18.0
2         3     moscow, yukon territory, russia   NaN
3         4           porto, v.n.gaia, portugal  17.0
4         5  farnborough, hants, united kingdom   NaN
5         6       santa monica, california, usa  61.0
6         7                 washington, dc, usa   NaN
7         8            timmins, ontario, canada   NaN
8         9          germantown, tennessee, usa   NaN
9        10          albacete, wisconsin, spain  26.0
10       11      melbourne, victoria, australia  14.0
11       12         fort bragg, california, usa   NaN
12       13         barcelona, barcelona, spain  26.0

In [23]:
book

,ISBN,Title,Author,Published-Year,Publisher,URL-S,URL-M,URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

In [24]:
book.loc[book.duplicated(subset='Title')]
#book.query('Title=="James and the Giant Peach"')

,ISBN,Title,Author,Published-Year,Publisher,URL-S,URL-M,URL-L
239,0743486226,Angels &amp; Demons,Dan Brown,2003,Atria,http://images.amazon.com/images/P/0743486226.0...,http://images.amazon.com/images/P/0743486226.0...,http://images.amazon.com/images/P/0743486226.0...
355,0140374248,James and the Giant Peach,Roald Dahl,2000,Penguin USA (Paper),http://images.amazon.com/images/P/0140374248.0...,http://images.amazon.com/images/P/0140374248.0...,http://images.amazon.com/images/P/0140374248.0...
405,006101351X,The Perfect Storm : A True Story of Men Agains...,Sebastian Junger,1998,HarperTorch,http://images.amazon.com/images/P/006101351X.0...,http://images.amazon.com/images/P/006101351X.0...,http://images.amazon.com/images/P/006101351X.0...
456,044021145X,The Firm,John Grisham,1992,Bantam Dell Publishing Group,http://images.amazon.com/images/P/044021145X.0...,http://images.amazon.com/images/P/044021145X.0...,http://images.amazon.com/images/P/044021145X.0...
475,014023828X,The Tortilla Curtain,T. Coraghessan Boyle,1996,Penguin Books,http://images.amazon.com/images/P/014023828X.0...,http://images.amazon.com/images/P/014023828X.0...,http://images.amazon.com/images/P/014023828X.0...
...,...,...,...,...,...,...,...,...
271246,0195124995,For Cause and Comrades: Why Men Fought in the ...,James M. McPherson,1998,Oxford University Press,http://images.amazon.com/images/P/0195124995.0...,http://images.amazon.com/images/P/0195124995.0...,http://images.amazon.com/images/P/0195124995.0...
271315,1902852036,All the Queen's Men,Nick Elwood,1999,Gay Men's Press,http://images.amazon.com/images/P/1902852036.0...,http://images.amazon.com/images/P/1902852036.0...,http://images.amazon.com/images/P/1902852036.0...
271316,0441011799,Singularity Sky,Charles Stross,2004,Ace,http://images.amazon.com/images/P/0441011799.0...,http://images.amazon.com/images/P/0441011799.0...,http://images.amazon.com/images/P/0441011799.0...
271346,0395264707,Dreamsnake,Vonda N. McIntyre,1978,Houghton Mifflin,http://images.amazon.com/images/P/0395264707.0...,http://images.amazon.com/images/P/0395264707.0...,http://images.amazon.com/images/P/0395264707.0...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...

Model Building

In [51]:
rating_name=rating.merge(book,on='ISBN')
numRatingBook=rating_name.groupby('Title').count()['User-ID'].reset_index()
numRatingBook.rename(columns={'User-ID':'Rating Count'},inplace=True)
numRatingBook

                                                    Title  Rating Count
0        A Light in the Storm: The Civil War Diary of ...             4
1                                   Always Have Popsicles             1
2                    Apple Magic (The Collector's series)             1
3        Ask Lily (Young Women of Faith: Lily Series, ...             1
4        Beyond IBM: Leadership Marketing and Finance ...             1
...                                                   ...           ...
241066                                      Ã?Â?lpiraten.             2
241067                     Ã?Â?rger mit Produkt X. Roman.             4
241068                                Ã?Â?sterlich leben.             1
241069                              Ã?Â?stlich der Berge.             3
241070                                  Ã?Â?thique en toc             2

[241071 rows x 2 columns]

In [85]:
avgRatingBook=rating_name.groupby('Title')['Book-Rating'].mean().reset_index()
avgRatingBook.rename(columns={'Book-Rating':'Rating Avg'},inplace=True)
avgRatingBook

                                                    Title  Rating Avg
0        A Light in the Storm: The Civil War Diary of ...    2.250000
1                                   Always Have Popsicles    0.000000
2                    Apple Magic (The Collector's series)    0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...    8.000000
4        Beyond IBM: Leadership Marketing and Finance ...    0.000000
...                                                   ...         ...
241066                                      Ã?Â?lpiraten.    0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.    5.250000
241068                                Ã?Â?sterlich leben.    7.000000
241069                              Ã?Â?stlich der Berge.    2.666667
241070                                  Ã?Â?thique en toc    4.000000

[241071 rows x 2 columns]

In [129]:
ratingNew = numRatingBook.merge(avgRatingBook, on=('Title')) #60 popular books based on ratings and also popularity based recommendation
ratingNew=ratingNew[ratingNew['Rating Count']>249].sort_values('Rating Avg',ascending=False).head(60)
ratingNew

,Title,Rating Count,Rating Avg
80434,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804
80422,Harry Potter and the Goblet of Fire (Book 4),387,5.824289
80441,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410
80426,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441
80414,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453
191612,The Hobbit : The Enchanting Prelude to The Lor...,281,5.007117
187377,The Fellowship of the Ring (The Lord of the Ri...,368,4.948370
80445,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652
211384,"The Two Towers (The Lord of the Rings, Part 2)",260,4.880769
219741,To Kill a Mockingbird,510,4.700000
183573,The Da Vinci Code,898,4.642539
187880,The Five People You Meet in Heaven,430,4.551163
180556,The Catcher in the Rye,449,4.545657
196326,The Lovely Bones: A Novel,1295,4.468726
764,1984,284,4.454225
144165,Prodigal Summer: A Novel,253,4.450593
128670,Neverwhere,265,4.449057
206502,The Secret Life of Bees,774,4.447028
168719,Stupid White Men ...and Other Sorry Excuses fo...,283,4.356890
223135,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970
204387,The Red Tent (Bestselling Backlist),723,4.334716
191589,The Hitchhiker's Guide to the Galaxy,268,4.328358
129379,Nickel and Dimed: On (Not) Getting By in America,335,4.289552
93381,Into the Wild,252,4.273810
63867,Fahrenheit 451,409,4.264059
74750,Girl with a Pearl Earring,526,4.218631
136145,Outlander,283,4.173145
233370,Where the Heart Is (Oprah's Book Club (Paperba...,585,4.105983
156102,Seabiscuit: An American Legend,275,4.098182
107962,Life of Pi,664,4.088855
176845,The Bean Trees,389,4.087404
2281,"A Child Called \It\"": One Child's Courage to S...",265,4.086792
8434,ANGELA'S ASHES,279,4.075269
76343,Good in Bed,490,4.055102
64931,Fast Food Nation: The Dark Side of the All-Ame...,321,4.037383
12700,American Gods,302,4.006623
161645,Skipping Christmas,322,4.006211
105777,Left Behind: A Novel of the Earth's Last Days ...,318,4.003145
189551,"The Golden Compass (His Dark Materials, Book 1)",336,4.000000
181679,The Color Purple,314,3.964968
160336,Silence of the Lambs,256,3.960938
8752,About a Boy,262,3.900763
158138,Seven Up (A Stephanie Plum Novel),278,3.888489
175097,The Alchemist: A Fable About Following Your Dream,266,3.875940
80069,Hard Eight : A Stephanie Plum Novel (A Stephan...,269,3.825279
170101,Suzanne's Diary for Nicholas,457,3.820569
111073,Lord of the Flies,259,3.818533
5664,A Prayer for Owen Meany,413,3.796610
212070,"The Vampire Lestat (Vampire Chronicles, Book II)",301,3.777409
233851,White Oleander : A Novel (Oprah's Book Club),356,3.772472
234740,Wicked: The Life and Times of the Wicked Witch...,326,3.766871
118237,Me Talk Pretty One Day,457,3.752735
219349,Timeline,552,3.750000
121143,Misery,291,3.718213
14392,Angels &amp; Demons,670,3.708955
21754,Bel Canto: A Novel,350,3.702857
230246,Watership Down,312,3.698718
190334,The Green Mile,264,3.681818
19780,Balzac and the Little Chinese Seamstress : A N...,284,3.676056
134493,One for the Money (Stephanie Plum Novels (Pape...,291,3.656357

In [159]:
pop_data=ratingNew.merge(book,on=('Title')).drop_duplicates('Title')
pop_data=pop_data[['Title','Rating Count','Rating Avg','ISBN','Author','Published-Year','URL-M']].reset_index(drop=True)
pop_data

,Title,Rating Count,Rating Avg,ISBN,Author,Published-Year,URL-M
0,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804,0439136350,J. K. Rowling,1999,http://images.amazon.com/images/P/0439136350.0...
1,Harry Potter and the Goblet of Fire (Book 4),387,5.824289,0439139597,J. K. Rowling,2000,http://images.amazon.com/images/P/0439139597.0...
2,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410,0590353403,J. K. Rowling,1998,http://images.amazon.com/images/P/0590353403.0...
3,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441,043935806X,J. K. Rowling,2003,http://images.amazon.com/images/P/043935806X.0...
4,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453,0439064872,J. K. Rowling,2000,http://images.amazon.com/images/P/0439064872.0...
5,The Hobbit : The Enchanting Prelude to The Lor...,281,5.007117,0345339681,J.R.R. TOLKIEN,1986,http://images.amazon.com/images/P/0345339681.0...
6,The Fellowship of the Ring (The Lord of the Ri...,368,4.948370,0345339703,J.R.R. TOLKIEN,1986,http://images.amazon.com/images/P/0345339703.0...
7,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652,059035342X,J. K. Rowling,1999,http://images.amazon.com/images/P/059035342X.0...
8,"The Two Towers (The Lord of the Rings, Part 2)",260,4.880769,0345339711,J.R.R. TOLKIEN,1986,http://images.amazon.com/images/P/0345339711.0...
9,To Kill a Mockingbird,510,4.700000,0446310786,Harper Lee,1988,http://images.amazon.com/images/P/0446310786.0...
10,The Da Vinci Code,898,4.642539,0385504209,Dan Brown,2003,http://images.amazon.com/images/P/0385504209.0...
11,The Five People You Meet in Heaven,430,4.551163,0786868716,Mitch Albom,2003,http://images.amazon.com/images/P/0786868716.0...
12,The Catcher in the Rye,449,4.545657,0316769487,J.D. Salinger,1991,http://images.amazon.com/images/P/0316769487.0...
13,The Lovely Bones: A Novel,1295,4.468726,0316666343,Alice Sebold,2002,http://images.amazon.com/images/P/0316666343.0...
14,1984,284,4.454225,0451524934,George Orwell,1990,http://images.amazon.com/images/P/0451524934.0...
15,Prodigal Summer: A Novel,253,4.450593,0060959037,Barbara Kingsolver,2001,http://images.amazon.com/images/P/0060959037.0...
16,Neverwhere,265,4.449057,0380789019,Neil Gaiman,1998,http://images.amazon.com/images/P/0380789019.0...
17,The Secret Life of Bees,774,4.447028,0142001740,Sue Monk Kidd,2003,http://images.amazon.com/images/P/0142001740.0...
18,Stupid White Men ...and Other Sorry Excuses fo...,283,4.356890,0060392452,Michael Moore,2002,http://images.amazon.com/images/P/0060392452.0...
19,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970,0385484518,MITCH ALBOM,1997,http://images.amazon.com/images/P/0385484518.0...
20,The Red Tent (Bestselling Backlist),723,4.334716,0312195516,Anita Diamant,1998,http://images.amazon.com/images/P/0312195516.0...
21,The Hitchhiker's Guide to the Galaxy,268,4.328358,0671461494,Douglas Adams,1982,http://images.amazon.com/images/P/0671461494.0...
22,Nickel and Dimed: On (Not) Getting By in America,335,4.289552,0805063897,Barbara Ehrenreich,2002,http://images.amazon.com/images/P/0805063897.0...
23,Into the Wild,252,4.273810,0385486804,Jon Krakauer,1997,http://images.amazon.com/images/P/0385486804.0...
24,Fahrenheit 451,409,4.264059,3257208626,Ray Bradbury,1994,http://images.amazon.com/images/P/3257208626.0...
25,Girl with a Pearl Earring,526,4.218631,0452282152,Tracy Chevalier,2001,http://images.amazon.com/images/P/0452282152.0...
26,Outlander,283,4.173145,0440222915,DIANA GABALDON,1996,http://images.amazon.com/images/P/0440222915.0...
27,Where the Heart Is (Oprah's Book Club (Paperba...,585,4.105983,0446672211,Billie Letts,1998,http://images.amazon.com/images/P/0446672211.0...
28,Seabiscuit: An American Legend,275,4.098182,0449005615,LAURA HILLENBRAND,2002,http://images.amazon.com/images/P/0449005615.0...
29,Life of Pi,664,4.088855,0151008116,Yann Martel,2002,http://images.amazon.com/images/P/0151008116.0...
30,The Bean Trees,389,4.087404,0060915544,Barbara Kingsolver,1989,http://images.amazon.com/images/P/0060915544.0...
31,"A Child Called \It\"": One Child's Courage to S...",265,4.086792,1558743669,Dave Pelzer,1995,http://images.amazon.com/images/P/1558743669.0...
32,ANGELA'S ASHES,279,4.075269,0684874350,Frank McCourt,1996,http://images.amazon.com/images/P/0684874350.0...
33,Good in Bed,490,4.055102,0743418174,Jennifer Weiner,2002,http://images.amazon.com/images/P/0743418174.0...
34,Fast Food Nation: The Dark Side of the All-Ame...,321,4.037383,0060938455,Eric Schlosser,2002,http://images.amazon.com/images/P/0060938455.0...
35,American Gods,302,4.006623,0380789035,Neil Gaiman,2002,http://images.amazon.com/images/P/0380789035.0...
36,Skipping Christmas,322,4.006211,0385505833,JOHN GRISHAM,2001,http://images.amazon.com/images/P/0385505833.0...
37,Left Behind: A Novel of the Earth's Last Days ...,318,4.003145,0842329129,Tim Lahaye,1996,http://images.amazon.com/images/P/0842329129.0...
38,"The Golden Compass (His Dark Materials, Book 1)",336,4.000000,037582345X,PHILIP PULLMAN,2002,http://images.amazon.com/images/P/037582345X.0...
39,The Color Purple,314,3.964968,0671617028,Alice Walker,1985,http://images.amazon.com/images/P/0671617028.0...
40,Silence of the Lambs,256,3.960938,0312924585,Thomas Harris,1991,http://images.amazon.com/images/P/0312924585.0...
41,About a Boy,262,3.900763,1573227331,Nick Hornby,1999,http://images.amazon.com/images/P/1573227331.0...
42,Seven Up (A Stephanie Plum Novel),278,3.888489,0312265840,Janet Evanovich,2001,http://images.amazon.com/images/P/0312265840.0...
43,The Alchemist: A Fable About Following Your Dream,266,3.875940,0062502174,Paulo Coelho,1993,http://images.amazon.com/images/P/0062502174.0...
44,Hard Eight : A Stephanie Plum Novel (A Stephan...,269,3.825279,0312983867,Janet Evanovich,2003,http://images.amazon.com/images/P/0312983867.0...
45,Suzanne's Diary for Nicholas,457,3.820569,0316969443,James Patterson,2001,http://images.amazon.com/images/P/0316969443.0...
46,Lord of the Flies,259,3.818533,0399501487,William Gerald Golding,1959,http://images.amazon.com/images/P/0399501487.0...
47,A Prayer for Owen Meany,413,3.796610,0345361792,John Irving,1990,http://images.amazon.com/images/P/0345361792.0...
48,"The Vampire Lestat (Vampire Chronicles, Book II)",301,3.777409,0345313860,ANNE RICE,1986,http://images.amazon.com/images/P/0345313860.0...
49,White Oleander : A Novel (Oprah's Book Club),356,3.772472,0316284955,Janet Fitch,2000,http://images.amazon.com/images/P/0316284955.0...
50,Wicked: The Life and Times of the Wicked Witch...,326,3.766871,0060987103,Gregory Maguire,1996,http://images.amazon.com/images/P/0060987103.0...
51,Me Talk Pretty One Day,457,3.752735,0316776963,David Sedaris,2001,http://images.amazon.com/images/P/0316776963.0...
52,Timeline,552,3.750000,0345417623,MICHAEL CRICHTON,2000,http://images.amazon.com/images/P/0345417623.0...
53,Misery,291,3.718213,0451153553,Stephen King,1988,http://images.amazon.com/images/P/0451153553.0...
54,Angels &amp; Demons,670,3.708955,0671027360,Dan Brown,2001,http://images.amazon.com/images/P/0671027360.0...
55,Bel Canto: A Novel,350,3.702857,0060934417,Ann Patchett,2002,http://images.amazon.com/images/P/0060934417.0...
56,Watership Down,312,3.698718,038039586X,Richard George Adams,1975,http://images.amazon.com/images/P/038039586X.0...
57,The Green Mile,264,3.681818,0671032658,Stephen King,1999,http://images.amazon.com/images/P/0671032658.0...
58,Balzac and the Little Chinese Seamstress : A N...,284,3.676056,0385722206,DAI SIJIE,2002,http://images.amazon.com/images/P/0385722206.0...
59,One for the Money (Stephanie Plum Novels (Pape...,291,3.656357,0061009059,Janet Evanovich,1995,http://images.amazon.com/images/P/0061009059.0...

Collaborative approach


-only users who have rated more than 230 books
-only books which have recieved atleast 50 votes

In [238]:
userRatedBooks=rating_name.groupby('User-ID').count()
top230users=userRatedBooks.loc[userRatedBooks['Book-Rating']>=230].index
top230users

Index([   254,   2276,   2766,   3363,   4385,   6251,   6543,   6575,   7158,
         7286,
       ...
       271705, 273979, 274004, 274061, 274301, 274308, 275970, 277427, 277639,
       278418],
      dtype='int64', name='User-ID', length=697)

In [252]:
filterRating= rating_name[rating_name['User-ID'].isin(top230users)]
filterRating

,User-ID,ISBN,Book-Rating,Title,Author,Published-Year,Publisher,URL-S,URL-M,URL-L
1150,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...
1151,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...,http://images.amazon.com/images/P/0026217457.0...,http://images.amazon.com/images/P/0026217457.0...
1152,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,http://images.amazon.com/images/P/003008685X.0...,http://images.amazon.com/images/P/003008685X.0...,http://images.amazon.com/images/P/003008685X.0...
1153,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982,Henry Holt &amp; Co,http://images.amazon.com/images/P/0030615321.0...,http://images.amazon.com/images/P/0030615321.0...,http://images.amazon.com/images/P/0030615321.0...
1154,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002,Avon Books,http://images.amazon.com/images/P/0060002050.0...,http://images.amazon.com/images/P/0060002050.0...,http://images.amazon.com/images/P/0060002050.0...
...,...,...,...,...,...,...,...,...,...,...
1029357,275970,1931868123,0,There's a Porcupine in My Outhouse: Misadventu...,Mike Tougias,2002,Capital Books (VA),http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...
1029358,275970,3411086211,10,Die Biene.,Sybil GrÃ?Â¤fin SchÃ?Â¶nfeldt,1993,"Bibliographisches Institut, Mannheim",http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...
1029359,275970,3829021860,0,The Penis Book,Joseph Cohen,1999,Konemann,http://images.amazon.com/images/P/3829021860.0...,http://images.amazon.com/images/P/3829021860.0...,http://images.amazon.com/images/P/3829021860.0...
1029360,275970,4770019572,0,Musashi,Eiji Yoshikawa,1995,Kodansha International (JPN),http://images.amazon.com/images/P/4770019572.0...,http://images.amazon.com/images/P/4770019572.0...,http://images.amazon.com/images/P/4770019572.0...
1029361,275970,9626340762,8,Northanger Abbey (Classic Literature with Clas...,Jane Austen,1996,Naxos Audiobooks Ltd.,http://images.amazon.com/images/P/9626340762.0...,http://images.amazon.com/images/P/9626340762.0...,http://images.amazon.com/images/P/9626340762.0...

In [274]:
y=filterRating.groupby('Title').count()['Book-Rating']>=50
famousBooks=y[y]

In [278]:
famousBooks=famousBooks.index

In [294]:
finalModel=filterRating[filterRating['Title'].isin(famousBooks)]
ptable= finalModel.pivot_table(index='Title', columns='User-ID', values='Book-Rating')

In [296]:
ptable.fillna(0, inplace=True)

In [298]:
ptable

User-ID,254,2276,2766,3363,4385,6251,6543,6575,7158,7286,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [302]:
from sklearn.metrics.pairwise import cosine_similarity as cos

In [314]:
cosTable=cos(ptable)

In [312]:
cos(ptable).shape

(626, 626)

In [316]:
cosTable

array([[1.        , 0.11601718, 0.01359243, ..., 0.13067822, 0.07928471,
        0.04908619],
       [0.11601718, 1.        , 0.25578759, ..., 0.0780675 , 0.17586244,
        0.15761227],
       [0.01359243, 0.25578759, 1.        , ..., 0.04703635, 0.05095527,
        0.11740378],
       ...,
       [0.13067822, 0.0780675 , 0.04703635, ..., 1.        , 0.07085128,
        0.02067643],
       [0.07928471, 0.17586244, 0.05095527, ..., 0.07085128, 1.        ,
        0.11175181],
       [0.04908619, 0.15761227, 0.11740378, ..., 0.02067643, 0.11175181,
        1.        ]])

In [378]:
def recom(bookName):
    index = np.where(ptable.index==bookName)[0][0]
    similiar= sorted(list(enumerate(cosTable[index])),key=lambda x:x[1],reverse=True)[1:8]
    data=[]
    for i in similiar:
        item=[]
        temp=book[book["Title"]==ptable.index[i[0]]]
        item.extend(list(temp.drop_duplicates('Title')['Title'].values))
        item.extend(list(temp.drop_duplicates('Title')['Author'].values))
        item.extend(list(temp.drop_duplicates('Title')['URL-L'].values))
        item.extend(list(temp.drop_duplicates('Title')['Published-Year'].values))
        data.append(item)
    return data

In [380]:
recom('Message in a Bottle')

[['Nights in Rodanthe',
  'Nicholas Sparks',
  'http://images.amazon.com/images/P/0446531332.01.LZZZZZZZ.jpg',
  2002],
 ['A Walk to Remember',
  'Nicholas Sparks',
  'http://images.amazon.com/images/P/0446608955.01.LZZZZZZZ.jpg',
  2000],
 ['The Mulberry Tree',
  'Jude Deveraux',
  'http://images.amazon.com/images/P/0743437640.01.LZZZZZZZ.jpg',
  2003],
 ["River's End",
  'Nora Roberts',
  'http://images.amazon.com/images/P/0515127833.01.LZZZZZZZ.jpg',
  2003],
 ['Nightmares &amp; Dreamscapes',
  'Stephen King',
  'http://images.amazon.com/images/P/0451180232.01.LZZZZZZZ.jpg',
  2004],
 ['Sanctuary',
  'Nora Roberts',
  'http://images.amazon.com/images/P/0515122734.01.LZZZZZZZ.jpg',
  2004],
 ['All I Really Need to Know',
  'ROBERT FULGHUM',
  'http://images.amazon.com/images/P/080410526X.01.LZZZZZZZ.jpg',
  1989]]

In [346]:
import pickle

In [350]:
pickle.dump(pop_data,open('popular.pkl','wb'))

In [384]:
pickle.dump(ptable,open('ptable.pkl','wb'))
pickle.dump(book,open('book.pkl','wb'))
pickle.dump(cosTable,open('costable.pkl','wb'))